name: SuOmic
run-name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        required: false
        default: false

jobs:
  running_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
